name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-3-87-123-140.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@ec2-3-87-123-140.compute-1.amazonaws.com << 'EOF'
          cd /var/www/html/laravel-ec2-cicd-pipeline-implementation
          git pull origin main
          npm install
          npm run build
          composer install
          php artisan migrate
          sudo systemctl restart nginx
          EOF
